version: "3.8"

services:
  usersdb:
    container_name: usersdb
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    restart: always
    ports:
        - "5433:5432"
    volumes:
      - postgres_users:/var/lib/postgresql/data/ 
    networks:
      - eventsapp-network
  
  eventsdb:
    container_name: eventsdb
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=events
    restart: always
    ports:
        - "5434:5432"
    volumes:
      - postgres_events:/var/lib/postgresql/data/ 
    networks:
      - eventsapp-network
  

  notificationsdb:
    container_name: notificationsdb
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=notifications
    restart: always
    ports:
        - "5435:5432"
    volumes:
      - postgres_notifications:/var/lib/postgresql/data/ 
    networks:
      - eventsapp-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      - eventsapp-network
     
  
  users.api:
    image: user.api
    build:
      context: .
      dockerfile: ./Services/Users/Users.API/Dockerfile
    environment:
      - JwtOptions__SecretKey=qwertyuiopasdfghjklzxcbnmabcdefjhijklmnop
      - JwtOptions__Issue=issuer
      - JwtOptions__Audience=audience
      - JwtOptions__AccessTokenExpirationMinutes=30
      - JwtOptions__RefreshTokenExpirationDays=7
      - ConnectionStrings__UsersDbContext=Host=usersdb;Port=5432;Database=users;Username=postgres;Password=postgres
      - ASPNETCORE_ENVIRONMENT=Development
    restart: on-failure
    ports:
      - "8081:8080"
    volumes:
      - ./.aspnet/users.api/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
    networks:
      - eventsapp-network
    depends_on:
      - usersdb

  events.api:
    image: events.api
    build:
      context: .
      dockerfile: ./Services/Events/Events.API/Dockerfile
    environment:
      - JwtOptions__SecretKey=qwertyuiopasdfghjklzxcbnmabcdefjhijklmnop
      - JwtOptions__Issue=issuer
      - JwtOptions__Audience=audience
      - JwtOptions__AccessTokenExpirationMinutes=30
      - JwtOptions__RefreshTokenExpirationDays=7
      - ConnectionStrings__EventsDbContext=Host=eventsdb;Port=5432;Database=events;Username=postgres;Password=postgres
      - ASPNETCORE_ENVIRONMENT=Development
    restart: on-failure
    ports:
      - "8082:8080"
    volumes:
      - ./Uploads:/app/Uploads
      - ./.aspnet/events.api/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
    networks:
      - eventsapp-network
    depends_on:
      - eventsdb
      - rabbitmq

  notifications.api:
    image: notifications.api
    build:
      context: .
      dockerfile: ./Services/Notification/notifications.API/Dockerfile
    environment:
      - JwtOptions__SecretKey=qwertyuiopasdfghjklzxcbnmabcdefjhijklmnop
      - JwtOptions__Issue=issuer
      - JwtOptions__Audience=audience
      - JwtOptions__AccessTokenExpirationMinutes=30
      - JwtOptions__RefreshTokenExpirationDays=7
      - ConnectionStrings__NotificationsDbContext=Host=notificationsdb;Port=5432;Database=notifications;Username=postgres;Password=postgres
      - RabbitMQ__Host=rabbitmq://rabbitmq
      - RabbitMQ__Password=guest
      - RabbitMQ__UserName=guest
      - ASPNETCORE_ENVIRONMENT=Development
    restart: on-failure
    ports:
      - "8083:8080"
    volumes:
      - ./.aspnet/notifications.api/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
    networks:
      - eventsapp-network
    depends_on:
      - notificationsdb
      - rabbitmq

networks:
  eventsapp-network:

volumes:
  rabbitmq:
  postgres_notifications:
  postgres_users:
  postgres_events:
